//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restauranteASP
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mesa_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mesa_()
        {
            this.Pedido = new HashSet<Pedido_>();
        }



        [Range(1, 999)]
        [Display(Name = "Número")]
        public int idMesa { get; set; }
        [Required]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [Display(Name = "Estado")]
        public Nullable<int> idEstado { get; set; }
        [Required]
        [Range(1, 999)]
        [Display(Name = "Capacidad de Personas")]
        public Nullable<int> capacidadPersona { get; set; }

        [Display(Name = "Estado")]
        public virtual MesaEstado_ MesaEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Pedido_> Pedido { get; set; }
    }
}
