//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restauranteASP
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PedidoDetalle_
    {
      
        public int idPedido { get; set; }
        public int idArticulo { get; set; }
        [Range(1, 999)]
        [Display(Name = "Numero Factura")]
        public int secuencia { get; set; }        
        [Display(Name = "Precio Unitario")]
        public Nullable<decimal> precioUnitario { get; set; }        
        [Display(Name = "Cantidad")]
        public Nullable<decimal> cantidad { get; set; }        
        [Display(Name = "SubTotal")]
        public Nullable<decimal> subTotal { get; set; }      
        [Display(Name = "Porcentaje Descuento")]
        public Nullable<decimal> porcentajeDescuento { get; set; }  
        [Display(Name = "Impuesto")]
        public Nullable<decimal> impuesto { get; set; }
        [Display(Name = "Total")]
        public Nullable<decimal> total { get; set; }
        public virtual Articulo_ Articulo { get; set; }
        [JsonIgnore]
        public virtual Pedido_ Pedido { get; set; }
    }
}
