//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restauranteASP
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido_()
        {
            this.PedidoDetalle = new HashSet<PedidoDetalle_>();
        }
        [Range(1, 999)]
        [Display(Name = "Número")]
        public int idPedido { get; set; }

        [Display(Name = "Cliente")]
        public string idCliente { get; set; }
        
        [Display(Name = "Observación")]
        public string observacion { get; set; }
        [Range(1, 999)]
        [Display(Name = "Número Factura")]
        public Nullable<decimal> numeroFactura { get; set; }
        public Nullable<int> idMesa { get; set; }
        [Display(Name = "Estado")]
        public int idEstado { get; set; }
        public Nullable<int> idCaja { get; set; }

        [Display(Name = "Usuario")]
        public string usuario { get; set; }
        
        [Display(Name = "SubTotal")]
        public decimal subTotal { get; set; }
        
        [Display(Name = "Descuento")]
        public decimal descuento { get; set; }
        
        [Display(Name = "Impuesto")]
        public decimal impuesto { get; set; }
        
        [Display(Name = "Total")]
        public decimal total { get; set; }
    
        public virtual Caja_ Caja { get; set; }
        public virtual Cliente_ Cliente { get; set; }
        public virtual Mesa_ Mesa { get; set; }
        public virtual PedidoEstado_ PedidoEstado { get; set; }
        public virtual Usuario_ Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle_> PedidoDetalle { get; set; }
    }
}
