//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restauranteASP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDetalle_
    {
        public int idPedido { get; set; }
        public int idArticulo { get; set; }
        public int secuencia { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> subTotal { get; set; }
        public Nullable<decimal> porcentajeDescuento { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Articulo_ Articulo { get; set; }
        public virtual Pedido_ Pedido { get; set; }
    }
}
